In [2]:
import numpy as np
import pandas as pd
import statistics as st
from scipy.stats import zscore

In [3]:
exam_results = pd.read_csv('exam_dataset.csv', sep=';')
exam_results.head()
exam_results.tail()

,Years learning English,Months preparing for exam,Informal English exposure,Hours per week,Type of content,Exam type,Overall exam score,Listening score,Reading score,Speaking score,Writing Score
46,8.0,7.0,Yes,9.0,Series,IELTS,6.5,6.0,7.0,6.5,6.5
47,6.0,10.0,No,0.0,NaN,FCE,145.0,142.0,144.0,143.0,154.0
48,8.0,13.0,Yes,11.0,YouTube,IELTS,8.0,8.0,8.0,9.0,8.0
49,5.0,3.0,Yes,6.0,Films,TOEFL,17.0,20.0,22.0,18.0,20.0
50,5.0,NaN,Yes,1.0,NaN,FCE,NaN,NaN,NaN,NaN,NaN

In [ ]:
#exam_results.info()
#exam_results.isnull().sum()
#"Type of content" has missing values, but it is not a mistake. 
exam_results["Type of content"] = exam_results["Type of content"].fillna("No")
exam_results = exam_results.dropna()
exam_results.isnull().sum()
exam_results.info()
#noticed that there are 49 entries, but 45 rows. Index needs resetting.
exam_results.reset_index(drop=True) 
#Now we droped all the rows with missing values, which probably happened due to the fact that students did not answer some questions. We can also see that all the columns have the right type of content, so we can start our analysis.

<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 0 to 49
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Years learning English     45 non-null     float64
 1   Months preparing for exam  45 non-null     float64
 2   Informal English exposure  45 non-null     object
 3   Hours per week             45 non-null     float64
 4   Type of content            45 non-null     object
 5   Exam type                  45 non-null     object
 6   Overall exam score         45 non-null     float64
 7   Listening score            45 non-null     float64
 8   Reading score              45 non-null     float64
 9   Speaking score             45 non-null     float64
 10  Writing Score              45 non-null     float64
dtypes: float64(8), object(3)
memory usage: 4.2+ KB

,Years learning English,Months preparing for exam,Informal English exposure,Hours per week,Type of content,Exam type,Overall exam score,Listening score,Reading score,Speaking score,Writing Score
0,14.0,18.0,Yes,2.0,Series,IELTS,6.0,5.5,6.0,5.5,6.0
1,10.0,1.0,Yes,6.0,YouTube,IELTS,5.5,6.5,5.0,5.0,5.0
2,11.0,2.0,Yes,5.0,Short vids,IELTS,6.5,6.5,6.5,5.5,6.0
3,13.0,4.0,Yes,13.0,Films,TOEFL,96.0,27.0,25.0,21.0,23.0
4,9.0,18.0,No,0.0,No,TOEFL,76.0,19.0,20.0,17.0,20.0
5,12.0,13.0,Yes,14.0,YouTube,TOEFL,105.0,28.0,27.0,25.0,25.0
6,13.0,16.0,Yes,2.0,YouTube,IELTS,6.0,6.0,7.0,6.0,5.5
7,5.0,4.0,Yes,2.0,Short vids,FCE,168.0,170.0,165.0,175.0,162.0
8,3.0,13.0,No,0.0,No,FCE,141.0,142.0,140.0,142.0,141.0
9,6.0,7.0,Yes,4.0,YouTube,FCE,163.0,158.0,167.0,161.0,166.0
10,6.0,9.0,Yes,3.0,Short vids,TOEFL,56.0,19.0,15.0,15.0,7.0
11,13.0,1.0,No,0.0,No,FCE,160.0,158.0,154.0,149.0,152.0
12,13.0,12.0,No,0.0,No,IELTS,5.5,5.5,5.0,4.0,5.5
13,3.0,15.0,No,0.0,No,IELTS,5.5,3.5,3.5,3.5,5.5
14,8.0,12.0,Yes,3.0,Films,IELTS,6.0,6.0,6.0,5.5,6.0
15,12.0,3.0,Yes,14.0,Films,IELTS,7.0,8.0,7.0,6.5,6.0
16,4.0,10.0,Yes,13.0,Short vids,IELTS,7.5,7.5,7.5,6.5,7.5
17,12.0,5.0,No,0.0,No,IELTS,5.5,5.5,6.0,5.5,4.5
18,4.0,18.0,Yes,11.0,Films,TOEFL,96.0,21.0,19.0,18.0,19.0
19,8.0,16.0,Yes,9.0,Films,IELTS,6.0,6.0,5.0,5.5,6.0
20,12.0,4.0,No,0.0,No,TOEFL,72.0,11.0,10.0,7.0,18.0
21,6.0,10.0,Yes,12.0,YouTube,IELTS,7.0,7.0,6.5,6.5,7.0
22,7.0,17.0,Yes,14.0,Short vids,TOEFL,116.0,29.0,30.0,29.0,28.0
23,6.0,16.0,Yes,6.0,YouTube,IELTS,6.0,6.5,6.5,5.0,5.5
24,11.0,13.0,Yes,11.0,Short vids,IELTS,7.5,8.5,7.5,6.5,6.5
25,6.0,12.0,Yes,2.0,Series,FCE,160.0,158.0,158.0,149.0,166.0
26,14.0,1.0,Yes,4.0,YouTube,TOEFL,86.0,22.0,26.0,18.0,20.0
27,8.0,14.0,No,0.0,No,FCE,148.0,149.0,145.0,140.0,152.0
28,8.0,9.0,Yes,3.0,Films,TOEFL,86.0,25.0,25.0,16.0,20.0
29,9.0,2.0,Yes,8.0,Short vids,TOEFL,96.0,26.0,27.0,22.0,24.0
30,9.0,5.0,Yes,11.0,YouTube,IELTS,6.0,6.0,5.6,5.5,6.0
31,9.0,10.0,No,0.0,No,TOEFL,72.0,19.0,17.0,18.0,18.0
32,9.0,14.0,Yes,12.0,Short vids,IELTS,7.0,7.0,7.0,7.0,6.5
33,14.0,10.0,Yes,10.0,Films,FCE,181.0,182.0,186.0,170.0,179.0
34,12.0,12.0,Yes,5.0,Films,FCE,168.0,162.0,169.0,160.0,170.0
35,11.0,13.0,No,0.0,No,IELTS,5.5,5.0,5.5,4.5,6.0
36,10.0,7.0,Yes,13.0,Short vids,IELTS,6.5,7.5,6.0,7.0,5.5
37,7.0,12.0,Yes,5.0,YouTube,IELTS,6.0,6.0,7.0,5.5,5.5
38,8.0,2.0,No,0.0,No,TOEFL,69.0,17.0,18.0,17.0,17.0
39,4.0,5.0,No,0.0,No,TOEFL,92.0,24.0,27.0,20.0,21.0
40,3.0,3.0,No,0.0,No,FCE,160.0,157.0,160.0,163.0,167.0
41,8.0,7.0,Yes,9.0,Series,IELTS,6.5,6.0,7.0,6.5,6.5
42,6.0,10.0,No,0.0,No,FCE,145.0,142.0,144.0,143.0,154.0
43,8.0,13.0,Yes,11.0,YouTube,IELTS,8.0,8.0,8.0,9.0,8.0
44,5.0,3.0,Yes,6.0,Films,TOEFL,17.0,20.0,22.0,18.0,20.0

In [5]:
#Next huge problem - different tests are scored differently, but we need to make them comparable. 
# Z-score is a way to standardize scores on the same scale by converting them to a common scale with a mean of 0 and a standard deviation of 1. 
score_columns = [
    "Overall exam score",
    "Listening score",
    "Reading score",
    "Speaking score",
    "Writing Score"
]
for column in score_columns:
    exam_results[column + "_z"] = exam_results.groupby("Exam type")[column].transform(zscore)
exam_results

,Years learning English,Months preparing for exam,Informal English exposure,Hours per week,Type of content,Exam type,Overall exam score,Listening score,Reading score,Speaking score,Writing Score,Overall exam score_z,Listening score_z,Reading score_z,Speaking score_z,Writing Score_z
0,14.0,18.0,Yes,2.0,Series,IELTS,6.0,5.5,6.0,5.5,6.0,-0.457116,-0.784928,-0.233734,-0.269318,-0.030571
1,10.0,1.0,Yes,6.0,YouTube,IELTS,5.5,6.5,5.0,5.0,5.0,-1.142791,0.106071,-1.196166,-0.704370,-1.314548
2,11.0,2.0,Yes,5.0,Short vids,IELTS,6.5,6.5,6.5,5.5,6.0,0.228558,0.106071,0.247483,-0.269318,-0.030571
3,13.0,4.0,Yes,13.0,Films,TOEFL,96.0,27.0,25.0,21.0,23.0,0.636601,1.065893,0.547723,0.486083,0.645925
4,9.0,18.0,No,0.0,No,TOEFL,76.0,19.0,20.0,17.0,20.0,-0.216261,-0.615516,-0.365148,-0.338785,0.000000
5,12.0,13.0,Yes,14.0,YouTube,TOEFL,105.0,28.0,27.0,25.0,25.0,1.020389,1.276069,0.912871,1.310952,1.076541
6,13.0,16.0,Yes,2.0,YouTube,IELTS,6.0,6.0,7.0,6.0,5.5,-0.457116,-0.339428,0.728699,0.165734,-0.672560
7,5.0,4.0,Yes,2.0,Short vids,FCE,168.0,170.0,165.0,175.0,162.0,0.752997,1.058033,0.470345,1.698086,0.104743
8,3.0,13.0,No,0.0,No,FCE,141.0,142.0,140.0,142.0,141.0,-1.611063,-1.370240,-1.426208,-1.132057,-1.894894
10,6.0,7.0,Yes,4.0,YouTube,FCE,163.0,158.0,167.0,161.0,166.0,0.315208,0.017345,0.622070,0.497419,0.485626
11,6.0,9.0,Yes,3.0,Short vids,TOEFL,56.0,19.0,15.0,15.0,7.0,-1.069124,-0.615516,-1.278019,-0.751219,-2.799006
12,13.0,1.0,No,0.0,No,FCE,160.0,158.0,154.0,149.0,152.0,0.052535,0.017345,-0.364138,-0.531724,-0.847465
14,13.0,12.0,No,0.0,No,IELTS,5.5,5.5,5.0,4.0,5.5,-1.142791,-0.784928,-1.196166,-1.574475,-0.672560
16,3.0,15.0,No,0.0,No,IELTS,5.5,3.5,3.5,3.5,5.5,-1.142791,-2.566926,-2.639814,-2.009527,-0.672560
17,8.0,12.0,Yes,3.0,Films,IELTS,6.0,6.0,6.0,5.5,6.0,-0.457116,-0.339428,-0.233734,-0.269318,-0.030571
18,12.0,3.0,Yes,14.0,Films,IELTS,7.0,8.0,7.0,6.5,6.0,0.914232,1.442570,0.728699,0.600786,-0.030571
19,4.0,10.0,Yes,13.0,Short vids,IELTS,7.5,7.5,7.5,6.5,7.5,1.599907,0.997070,1.209915,0.600786,1.895395
20,12.0,5.0,No,0.0,No,IELTS,5.5,5.5,6.0,5.5,4.5,-1.142791,-0.784928,-0.233734,-0.269318,-1.956537
21,4.0,18.0,Yes,11.0,Films,TOEFL,96.0,21.0,19.0,18.0,19.0,0.636601,-0.195164,-0.547723,-0.132568,-0.215308
22,8.0,16.0,Yes,9.0,Films,IELTS,6.0,6.0,5.0,5.5,6.0,-0.457116,-0.339428,-1.196166,-0.269318,-0.030571
23,12.0,4.0,No,0.0,No,TOEFL,72.0,11.0,10.0,7.0,18.0,-0.386834,-2.296924,-2.190890,-2.400956,-0.430616
24,6.0,10.0,Yes,12.0,YouTube,IELTS,7.0,7.0,6.5,6.5,7.0,0.914232,0.551571,0.247483,0.600786,1.253407
25,7.0,17.0,Yes,14.0,Short vids,TOEFL,116.0,29.0,30.0,29.0,28.0,1.489463,1.486245,1.460593,2.135820,1.722466
26,6.0,16.0,Yes,6.0,YouTube,IELTS,6.0,6.5,6.5,5.0,5.5,-0.457116,0.106071,0.247483,-0.704370,-0.672560
27,11.0,13.0,Yes,11.0,Short vids,IELTS,7.5,8.5,7.5,6.5,6.5,1.599907,1.888070,1.209915,0.600786,0.611418
28,6.0,12.0,Yes,2.0,Series,FCE,160.0,158.0,158.0,149.0,166.0,0.052535,0.017345,-0.060690,-0.531724,0.485626
29,14.0,1.0,Yes,4.0,YouTube,TOEFL,86.0,22.0,26.0,18.0,20.0,0.210170,0.015013,0.730297,-0.132568,0.000000
31,8.0,14.0,No,0.0,No,FCE,148.0,149.0,145.0,140.0,152.0,-0.998158,-0.763172,-1.046898,-1.303581,-0.847465
32,8.0,9.0,Yes,3.0,Films,TOEFL,86.0,25.0,25.0,16.0,20.0,0.210170,0.645541,0.547723,-0.545002,0.000000
33,9.0,2.0,Yes,8.0,Short vids,TOEFL,96.0,26.0,27.0,22.0,24.0,0.636601,0.855717,0.912871,0.692300,0.861233
34,9.0,5.0,Yes,11.0,YouTube,IELTS,6.0,6.0,5.6,5.5,6.0,-0.457116,-0.339428,-0.618706,-0.269318,-0.030571
36,9.0,10.0,No,0.0,No,TOEFL,72.0,19.0,17.0,18.0,18.0,-0.386834,-0.615516,-0.912871,-0.132568,-0.430616
37,9.0,14.0,Yes,12.0,Short vids,IELTS,7.0,7.0,7.0,7.0,6.5,0.914232,0.551571,0.728699,1.035838,0.611418
38,14.0,10.0,Yes,10.0,Films,FCE,181.0,182.0,186.0,170.0,179.0,1.891247,2.098722,2.063450,1.269276,1.723497
39,12.0,12.0,Yes,5.0,Films,FCE,168.0,162.0,169.0,160.0,170.0,0.752997,0.364241,0.773794,0.411657,0.866509
40,11.0,13.0,No,0.0,No,IELTS,5.5,5.0,5.5,4.5,6.0,-1.142791,-1.230427,-0.714950,-1.139422,-0.030571
41,10.0,7.0,Yes,13.0,Short vids,IELTS,6.5,7.5,6.0,7.0,5.5,0.228558,0.997070,-0.233734,1.035838,-0.672560
42,7.0,12.0,Yes,5.0,YouTube,IELTS,6.0,6.0,7.0,5.5,5.5,-0.457116,-0.339428,0.728699,-0.269318,-0.672560
43,8.0,2.0,No,0.0,No,TOEFL,69.0,17.0,18.0,17.0,17.0,-0.514763,-1.035868,-0.730297,-0.338785,-0.645925
44,4.0,5.0,No,0.0,No,TOEFL,92.0,24.0,27.0,20.0,21.0,0.466028,0.435365,0.912871,0.279866,0.215308
45,3.0,3.0,No,0.0,No,FCE,160.0,157.0,160.0,163.0,167.0,0.052535,-0.069379,0.091035,0.668943,0.580847
46,8.0,7.0,Yes,9.0,Series,IELTS,6.5,6.0,7.0,6.5,6.5,0.228558,-0.339428,0.728699,0.600786,0.611418
47,6.0,10.0,No,0.0,No,FCE,145.0,142.0,144.0,143.0,154.0,-1.260832,-1.370240,-1.122760,-1.046295,-0.657024
48,8.0,13.0,Yes,11.0,YouTube,IELTS,8.0,8.0,8.0,9.0,8.0,2.285581,1.442570,1.691131,2.776047,2.537384
49,5.0,3.0,Yes,6.0,Films,TOEFL,17.0,20.0,22.0,18.0,20.0,-2.732205,-0.405340,0.000000,-0.132568,0.000000

In [6]:
#Now we can compare the score of the students with no media exposure to the students with media exposure. 

yes = exam_results[exam_results["Informal English exposure"] == "Yes"]["Overall exam score_z"]
no = exam_results[exam_results["Informal English exposure"] == "No"]["Overall exam score_z"]

#Independent Samples t-test?
#Null hypothesis
#Students with exposure and without exposure have the same mean score.
#Alternative hypothesis
#Students with exposure have different (or higher) scores.
from scipy.stats import ttest_ind
t_stat, p_value = ttest_ind(yes, no)
print(t_stat)
print(p_value)

if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant difference in scores between students with and without media exposure.")
    if yes.mean() > no.mean():
        print("Students with media exposure have higher scores on average.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference in scores between students with and without media exposure.")

3.3043631444924935
0.0019250425046234874
Reject the null hypothesis: There is a significant difference in scores between students with and without media exposure.
Students with media exposure have higher scores on average.

In [7]:
#Now when we know there is a significant difference, we can check the correlation between the scores and the media exposure, to see if there is a positive correlation between them: 
#the more hours of media exposure, the higher the score.
#We can use Pearson correlation coefficient for this.

In [8]:
from scipy.stats import pearsonr
r, p_value = pearsonr(exam_results["Hours per week"], exam_results["Overall exam score_z"])
print(p_value)

if p_value < 0.05:
    print("There is a significant correlation between hours of media exposure and overall exam scores.")
    if r > 0:
        print("The correlation is positive: as hours of media exposure increase, overall exam scores tend to increase.")
    else:
        print("The correlation is negative: as hours of media exposure increase, overall exam scores tend to decrease.")
else:
    print("There is no significant correlation between hours of media exposure and overall exam scores.")

3.1636643274788385e-06
There is a significant correlation between hours of media exposure and overall exam scores.
The correlation is positive: as hours of media exposure increase, overall exam scores tend to increase.

In [9]:
#There is a clear evidence that the increase in hours of media exposure is associated with an increase in overall exam scores.
#Now it seems reasonable to find the threshold of hours of media exposure that is associated with a significant increase in scores. We can use a simple linear regression for this.
unique_hours = sorted(exam_results["Hours per week"].unique())
unique_hours
#Now we got out unique values and we can build our "steps" to find a threshold.

[np.float64(0.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(6.0),
 np.float64(8.0),
 np.float64(9.0),
 np.float64(10.0),
 np.float64(11.0),
 np.float64(12.0),
 np.float64(13.0),
 np.float64(14.0)]

In [10]:
def exposure_group(hours):
    if hours <= 2:
        return "Low"
    elif hours <= 7:
        return "Medium"
    else:
        return "High"

exam_results["Exposure group"] = exam_results["Hours per week"].apply(exposure_group)
exam_results.head()
exam_results["Exposure group"].value_counts()
exam_results.groupby("Exposure group")["Overall exam score_z"].mean()

#To escape multiple comparisons problem - ANOVA test 
from scipy.stats import f_oneway
low = exam_results[exam_results["Exposure group"] == "Low"]["Overall exam score_z"]
med = exam_results[exam_results["Exposure group"] == "Medium"]["Overall exam score_z"]
high = exam_results[exam_results["Exposure group"] == "High"]["Overall exam score_z"]
f_stat, p_value = f_oneway(low, med, high)
if p_value < 0.05:
    print("There is a significant difference in overall exam scores among the different exposure groups.")
else:
    print("There is no significant difference in overall exam scores among the different exposure groups.")

#there is a significant difference between the groups, but we need to find out which groups are different from each other
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey = pairwise_tukeyhsd(endog=exam_results["Overall exam score_z"], groups=exam_results["Exposure group"], alpha=0.05)
print(tukey)

There is a significant difference in overall exam scores among the different exposure groups.
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
  High    Low   -1.407    0.0 -2.0598 -0.7542   True
  High Medium  -1.2982 0.0003 -2.0423  -0.554   True
   Low Medium   0.1088 0.9298 -0.6183   0.836  False
----------------------------------------------------

In [11]:
#High vs Medium = 1.2982 of mean difference, which is 1.3 standard deviations.
#Important to understand what does it mean in terms of actual points if we want target audience to understand the result.
one_exam_std = exam_results.groupby("Exam type")["Overall exam score"].std()
understandable_exact_exam_points = one_exam_std * 1.3
print(understandable_exact_exam_points)

Exam type
FCE      15.650474
IELTS     0.971382
TOEFL    31.636383
Name: Overall exam score, dtype: float64

The results of the Tukey HSD test show that there is a significant difference in overall exam scores between the Medium and High exposure groups. 
However, there is no significant difference between the Low and Medium exposure groups. 
This suggests that students with high media exposure have significantly higher overall exam scores compared to those with low or medium media exposure.
Precicely, 
1 hour a day makes a huge difference in exam scores.
Moreove, this 1 hour a day allows students to increase their result by:
FCE      16 points up
IELTS     1 full band up 
TOEFL    32 points up

In [12]:
#Okey obviously the results are astonishing. But which particular skills increase exactly? Does media exposure increase all the skills equally, or some skills more than others?

skills = [
    "Listening score_z",
    "Reading score_z",
    "Writing Score_z",
    "Speaking score_z"
]

for skill in skills:
    low = exam_results[exam_results["Exposure group"]=="Low"][skill]
    med = exam_results[exam_results["Exposure group"]=="Medium"][skill]
    high = exam_results[exam_results["Exposure group"]=="High"][skill]
    F, p_value = f_oneway(low, med, high)
    print(f"ANOVA shows for {skill}: F = {round(F,2)}, p = {round(p_value,4)}")

    tukey = pairwise_tukeyhsd(
        endog = exam_results[skill],
        groups = exam_results["Exposure group"],
        alpha = 0.05
    )
    print(f"Tuckey HSD for {skill}:")
    print(tukey.summary())
#According to Tuckey 
#Writing  → 1.16 SD
#Speaking → 1.08 SD
#Listening → 0.87 SD

ANOVA shows for Listening score_z: F = 18.1, p = 0.0
Tuckey HSD for Listening score_z:
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
  High    Low  -1.5678    0.0  -2.201 -0.9346   True
  High Medium  -0.8708 0.0147 -1.5926  -0.149   True
   Low Medium   0.6969 0.0534 -0.0083  1.4022  False
----------------------------------------------------
ANOVA shows for Reading score_z: F = 8.49, p = 0.0008
Tuckey HSD for Reading score_z:
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
  High    Low  -1.2284 0.0005 -1.9576 -0.4993   True
  High Medium  -0.5072 0.3095 -1.3384   0.324  False
   Low Medium   0.7212 0.0906  -0.091  1.5334  False
----------------------------------------------------
ANOVA shows for Writing Score_z: F = 10.9, p = 0.0002
Tuckey HSD for Writing Score_z:
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
  High    Low  -1.2525 0.0003 -1.9535 -0.5514   True
  High Medium  -1.1645 0.0028 -1.9637 -0.3654   True
   Low Medium   0.0879 0.9596 -0.6929  0.8688  False
----------------------------------------------------
ANOVA shows for Speaking score_z: F = 13.02, p = 0.0
Tuckey HSD for Speaking score_z:
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
  High    Low  -1.3842    0.0 -2.0631 -0.7053   True
  High Medium   -1.078 0.0044 -1.8519 -0.3041   True
   Low Medium   0.3062 0.5911   -0.45  1.0624  False
----------------------------------------------------

Media exposure is associated with higher writing scores, as well as speaking and listening scores (in exactly that order).
It could be suggested that frequent listening aids internalizing structures and increases motivations; students might mimic grammar and language structures, memorizing them better.

In [ ]:
#Which type of content is more effective?

,Years learning English,Months preparing for exam,Informal English exposure,Hours per week,Type of content,Exam type,Overall exam score,Listening score,Reading score,Speaking score,Writing Score,Overall exam score_z,Listening score_z,Reading score_z,Speaking score_z,Writing Score_z,Exposure group
0,14.0,18.0,Yes,2.0,Series,IELTS,6.0,5.5,6.0,5.5,6.0,-0.457116,-0.784928,-0.233734,-0.269318,-0.030571,Low
1,10.0,1.0,Yes,6.0,YouTube,IELTS,5.5,6.5,5.0,5.0,5.0,-1.142791,0.106071,-1.196166,-0.704370,-1.314548,Medium
2,11.0,2.0,Yes,5.0,Short vids,IELTS,6.5,6.5,6.5,5.5,6.0,0.228558,0.106071,0.247483,-0.269318,-0.030571,Medium
3,13.0,4.0,Yes,13.0,Films,TOEFL,96.0,27.0,25.0,21.0,23.0,0.636601,1.065893,0.547723,0.486083,0.645925,High
4,9.0,18.0,No,0.0,No,TOEFL,76.0,19.0,20.0,17.0,20.0,-0.216261,-0.615516,-0.365148,-0.338785,0.000000,Low

In [ ]:
exam_results["Type of content"].value_counts()

def content_type(string):
    if string == "YouTube":
        return "YB"
    elif string == "Short vids":
        return "Shorts"
    elif string == "Series" or string == "Films":
        return "Series/Films"
    else:
        return "Nothing"
    
exam_results["Content groups"] = exam_results["Type of content"].apply(content_type)

nothing = exam_results[exam_results["Content groups"]=="Nothing"]["Overall exam score_z"]
shorts = exam_results[exam_results["Content groups"]=="Shorts"]["Overall exam score_z"]
yb = exam_results[exam_results["Content groups"]=="YB"]["Overall exam score_z"]
series_films = exam_results[exam_results["Content groups"]=="Series/Films"]["Overall exam score_z"]
F, p_value = f_oneway(nothing, shorts, yb, series_films)

print(f"F = {round(F,2)}")
print(f"p = {p_value}") #p_value tells us content type is important, Tuckey to find out which one.

tukey = pairwise_tukeyhsd(
    endog=exam_results["Overall exam score_z"],
    groups=exam_results["Content groups"],
    alpha=0.05
)

print(tukey)

F = 4.55
p = 0.007653670501242585
      Multiple Comparison of Means - Tukey HSD, FWER=0.05
===============================================================
   group1       group2    meandiff p-adj   lower  upper  reject
---------------------------------------------------------------
     Nothing Series/Films   0.7712 0.1516 -0.1846 1.7271  False
     Nothing       Shorts   1.3786 0.0051  0.3406 2.4167   True
     Nothing           YB   0.8471 0.1258 -0.1589 1.8531  False
Series/Films       Shorts   0.6074 0.4363  -0.464 1.6788  False
Series/Films           YB   0.0758 0.9973 -0.9645 1.1162  False
      Shorts           YB  -0.5316 0.5837  -1.648 0.5848  False
---------------------------------------------------------------
Content groups
Nothing        -0.669629
Series/Films    0.101616
Shorts          0.709011
YB              0.177432
Name: Overall exam score_z, dtype: float64

Short-form video exposure is associated with significantly higher exam scores compared to none.
Other content types also show higher scores overall than no exposure, but these differences were not as drastic as shorts effect demonstrated.

In [ ]:
#Do students with many years learning English but low media exposure still score worse?
 

exam_results["High_years"] = exam_results["Years learning English"] >= 10

high_years_low_exposure = exam_results[
    (exam_results["High_years"] == True) &
    (exam_results["Exposure group"] == "Low")
]["Overall exam score_z"]

high_exposure_less_years = exam_results[
    (exam_results["Exposure group"] == "High") & (exam_results["Years learning English"] < 10)
]["Overall exam score_z"]

t_stat, p_value = ttest_ind(high_years_low_exposure, high_exposure_less_years)
print(f"t = {round(t_stat,2)}")
print(f"p = {p_value}")

if p_value < 0.05:
    print("There is a significant difference in overall exam scores between students with many years of learning English but low media exposure and students with high media exposure.")
    if high_years_low_exposure.mean() > high_exposure_less_years.mean():
        print("Students with many years of learning English but low media exposure have higher scores on average.")
    else:
        print("Students with high media exposure have higher scores on average even if they have fewer years of learning English.")

t = -3.96
p = 0.001256772093144505
There is a significant difference in overall exam scores between students with many years of learning English but low media exposure and students with high media exposure.
Students with high media exposure have higher scores on average.

Those engaging in video content more then 1 hour daily - but learned english for a shorter period of time then 10 years -  perform better then even those who spent more then 10 years learning English!

In [28]:
# Do student preparing for the exam with media exposure score better than students spending more time actually preparing fot the exam?

exam_results["High_preparation"] = exam_results["Months preparing for exam"] >= 6
high_preparation = exam_results[(exam_results["High_preparation"] == True) & (exam_results["Exposure group"] == "Low")]["Overall exam score_z"]
high_exposure_less_months_prep = exam_results[
    (exam_results["Exposure group"] == "High") & (exam_results["Months preparing for exam"] < 6)
]["Overall exam score_z"]

t_stat, p_value = ttest_ind(high_preparation, high_exposure_less_months_prep)
print(f"t = {round(t_stat,2)}")
print(f"p = {p_value}")
if p_value < 0.05:
    print("There is a significant difference in overall exam scores between students who prepared for the exam for 6 or more months and students with high media exposure.")
    if high_preparation.mean() > high_exposure_less_months_prep.mean():
        print("Students who prepared for the exam for 6 or more months have higher scores on average.")
    else:
        print("Students with high media exposure have higher scores on average.")

t = -3.87
p = 0.0019232807139371332
There is a significant difference in overall exam scores between students who prepared for the exam for 6 or more months and students with high media exposure.
Students with high media exposure have higher scores on average.

Those engaging in video content more then 1 hour daily perform better then even those who spent more time preparing.

In [32]:
exam_results.head()

#for illustration purposes

def exposure_hours_group(h):
    if h == 0:
        return "None"
    elif h <= 3:
        return "Low"
    elif h <= 7:
        return "Medium"
    else:
        return "High"

exam_results["Exposure_hours_group"] = exam_results["Hours per week"].apply(exposure_hours_group)


exam_results["Learning_strategy"] = "Other"
exam_results.loc[
    (exam_results["Months preparing for exam"] >= 6) &
    (exam_results["Exposure group"] == "Low"),
    "Learning_strategy"
] = "Long preparation"
exam_results.loc[
    (exam_results["Exposure group"] == "High") &
    (exam_results["Months preparing for exam"] < 6),
    "Learning_strategy"
] = "High exposure"

exam_results.head()

,Years learning English,Months preparing for exam,Informal English exposure,Hours per week,Type of content,Exam type,Overall exam score,Listening score,Reading score,Speaking score,...,Listening score_z,Reading score_z,Speaking score_z,Writing Score_z,Exposure group,Content groups,High_years,High_preparation,Exposure_hours_group,Learning_strategy
0,14.0,18.0,Yes,2.0,Series,IELTS,6.0,5.5,6.0,5.5,...,-0.784928,-0.233734,-0.269318,-0.030571,Low,Series/Films,True,True,Low,Long preparation
1,10.0,1.0,Yes,6.0,YouTube,IELTS,5.5,6.5,5.0,5.0,...,0.106071,-1.196166,-0.704370,-1.314548,Medium,YB,True,False,Medium,Other
2,11.0,2.0,Yes,5.0,Short vids,IELTS,6.5,6.5,6.5,5.5,...,0.106071,0.247483,-0.269318,-0.030571,Medium,Shorts,True,False,Medium,Other
3,13.0,4.0,Yes,13.0,Films,TOEFL,96.0,27.0,25.0,21.0,...,1.065893,0.547723,0.486083,0.645925,High,Series/Films,True,False,High,High exposure
4,9.0,18.0,No,0.0,No,TOEFL,76.0,19.0,20.0,17.0,...,-0.615516,-0.365148,-0.338785,0.000000,Low,Nothing,False,True,None,Long preparation

In [33]:
exam_results.to_csv("exam_results_clean.csv", index=False)